### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by danny-englander** [sparkbox/mediaCheck#17]
Thanks for this great plugin, it solves a lot of problems. I'd like to include this in a[ GPL v. 2.0](http://www.gnu.org/licenses/gpl-2.0.html) theme (drupal) but  did not see a license file. Ideally the Mit license would be good.

**Comment by robtarr** [comment]
I've added that info to the demo page and to the readme. Thanks for catching that.

https://creativecommons.org/licenses/by-sa/3.0/
