### ISSUE TITLE
Error in IE9

### ISSUE THREAD

**Issue by diego06884** [sparkbox/mediaCheck#23]
I am getting the following error in IE9:

SCRIPT5007: Unable to get value of the property 'appendChild': object is null or undefined 
mediaCheck.js, line 71 character 9

**Comment by robtarr** [comment]
Sorry for the delay, did you get it resolved? If you still need assistance, can you please post an example?

**Comment by diego06884** [comment]
Hi,
Sorry for taking so long responding. I had to change the code to make it work in IE9.
I had to change the document.body references (as in line 71 for example) to 
document.documentElement.getElementsByTagName("body")[0]
That removed the error.

**Comment by bryanbraun** [comment]
Glad you got it resolved. I believe this has been addressed in the library since you reported this, but feel free to reopen if you see it again.
