### ISSUE TITLE
Replace Grunt with NPM scripts

### ISSUE THREAD

**Issue by robtarr** [sparkbox/mediaCheck#36]

**Comment by shaungrady** [comment]
I'd be willing to lend a hand with this. To be clear, it looks like you want the following

- `npm test`
  - Run Jasmine
- ` npm start`
  - Transpile CoffeeScript
  - Prepend comment banner and output to `js/mediaCheck.js`
  - Watch for changes and repeat the above
- `npm run dist`
  - Transpile CoffeeScript
  - Prepend comment banner and output to `js/mediaCheck.js`

Is that correct?

**Comment by shaungrady** [comment]
This is ready to be closed 👍
